// Generated by gencpp from file esp32_motor_control/MotorCommand.msg
// DO NOT EDIT!


#ifndef ESP32_MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H
#define ESP32_MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esp32_motor_control
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : speed(0)
    , steps(0)
    , direction(false)
    , enable(false)  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : speed(0)
    , steps(0)
    , direction(false)
    , enable(false)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _steps_type;
  _steps_type steps;

   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::esp32_motor_control::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_motor_control::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::esp32_motor_control::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::esp32_motor_control::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::esp32_motor_control::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_motor_control::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_motor_control::MotorCommand_<ContainerAllocator1> & lhs, const ::esp32_motor_control::MotorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.steps == rhs.steps &&
    lhs.direction == rhs.direction &&
    lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_motor_control::MotorCommand_<ContainerAllocator1> & lhs, const ::esp32_motor_control::MotorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_motor_control::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_motor_control::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_motor_control::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "940b5105a71761b8262aeb4d75bf0d20";
  }

  static const char* value(const ::esp32_motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x940b5105a71761b8ULL;
  static const uint64_t static_value2 = 0x262aeb4d75bf0d20ULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_motor_control/MotorCommand";
  }

  static const char* value(const ::esp32_motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed\n"
"int32 steps\n"
"bool direction\n"
"bool enable\n"
;
  }

  static const char* value(const ::esp32_motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.steps);
      stream.next(m.direction);
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_motor_control::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_motor_control::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steps);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H
